// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Data;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621173018_StudentTableSeedData")]
    partial class StudentTableSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseTitle = "Mathematics",
                            Status = 0,
                            StudentName = "Alice Rahman",
                            TotalMarks = 45
                        },
                        new
                        {
                            Id = 2,
                            CourseTitle = "Physics",
                            Status = 1,
                            StudentName = "Tanvir Ahmed",
                            TotalMarks = 75
                        },
                        new
                        {
                            Id = 3,
                            CourseTitle = "English",
                            Status = 2,
                            StudentName = "Nusrat Jahan",
                            TotalMarks = 85
                        },
                        new
                        {
                            Id = 4,
                            CourseTitle = "Chemistry",
                            Status = 1,
                            StudentName = "Rafiul Islam",
                            TotalMarks = 68
                        },
                        new
                        {
                            Id = 5,
                            CourseTitle = "Biology",
                            Status = 2,
                            StudentName = "Mim Chowdhury",
                            TotalMarks = 88
                        },
                        new
                        {
                            Id = 6,
                            CourseTitle = "History",
                            Status = 0,
                            StudentName = "Mehedi Hasan",
                            TotalMarks = 33
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
