// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Data;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 17,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Rahman"
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            Email = "tanvir@example.com",
                            FirstName = "Tanvir",
                            LastName = "Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Email = "nusrat@example.com",
                            FirstName = "Nusrat",
                            LastName = "Jahan"
                        },
                        new
                        {
                            Id = 4,
                            Age = 18,
                            Email = "rafiul@example.com",
                            FirstName = "Rafiul",
                            LastName = "Islam"
                        },
                        new
                        {
                            Id = 5,
                            Age = 25,
                            Email = "mim@example.com",
                            FirstName = "Mim",
                            LastName = "Chowdhury"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
